version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  pythonpygame:
    docker:
      - image: feralbert90/pokepong1:latest  # Dockerfile que se necesita de dockerhub

jobs:
  job-tests:
    executor: pythonpygame
    steps:
      - checkout  # Para obtener el código del repositorio
      # Aquí agregamos los pasos para ejecutar tests, linting, análisis estático, etc.
      - run:
          name: Run tests
          command: | 
                    pytest Game/tests
      - run:
          name: Run linting
          command: | 
                    pylint  --exit-zero Game
      - run:
          name: Run code coverage
          command: |
                    coverage run -m pytest Game
                    coverage report -m 
      - store_test_results:
          path: Game/tests/test-results.xml
      - sonarcloud/scan

  job-deploy:
    docker:
      - image: feralbert90/pokepong1:latest
    steps:
      - checkout

       # Install Docker
      - run:
          name: Install Docker
          command: |
            apt-get update
            apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt-get update
            apt-get install -y docker-ce

      - run:
          name: Save Dockerfile as artifact
          command: |
                    mkdir -p artifacts
                    cp Game/Dockerfile artifacts/
      - run: 
          name: Build and tag Docker image
          command: |
                    docker build -t feralbert90/pokepong_artif:latest -f artifacts/Dockerfile .
      - run:
          name: Publish Docker image to Docker Hub
          command: |
                    echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker push feralbert90/pokepong_artif:latest


workflows:
  workflow-testing:
    jobs:
      - job-tests:
          context: SonarCloud
      - job-deploy:
          context: DockerHub
          requires:
            - job-tests
      # Agrega un trabajo para desplegar en Kubernetes usando ArgoCD
      # Este trabajo solo se ejecutará en la rama master/main
