version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  pythonpygame:
    docker:
      - image: feralbert90/pokepong1:latest  # Dockerfile que se necesita de dockerhub

jobs:
  job-tests:
    executor: pythonpygame
    steps:
      - checkout  # Para obtener el código del repositorio
      # Aquí agregamos los pasos para ejecutar tests, linting, análisis estático, etc.
      - run:
          name: Run tests
          command: | 
                    pytest Game/tests
      - run:
          name: Run linting
          command: | 
                    pylint  --exit-zero Game
      - run:
          name: Run code coverage
          command: |
                    coverage run -m pytest Game
                    coverage report -m 
      - store_test_results:
          path: Game/tests/test-results.xml
      - sonarcloud/scan

  job-deployment:
    executor: pythonpygame
    steps:
      - checkout
      - run:
          name: Install zip and GCloud SDK
          command: |
            apt-get update && apt-get install -y zip
            curl -sSL https://sdk.cloud.google.com | bash
            exec -l $SHELL
            gcloud auth activate-service-account --key-file=service-account-file.json
      - run:
          name: Upload artifact to Google Cloud Storage
          command: |
            mkdir -p artifacts
            zip -r artifacts/myapp.zip Game/*
            gsutil cp artifacts/myapp.zip gs://pokepong-circleci/
  
workflows:
  workflow-testing:
    jobs:
      - job-tests:
          context: SonarCloud
      - job-deployment:
          requires:
            - job-tests
          filters:
            tags:
              only: /*v.*/
            branches:
              only: main
      # Agrega un trabajo para desplegar en Kubernetes usando ArgoCD
      # Este trabajo solo se ejecutará en la rama master/mainn
