version: 2.1

executors:
  pythonpygame:
    docker:
      - image: feralbert90/pokepong1:latest  # Dockerfile que se necesita de dockerhub

jobs:
  job-testing:
    executor: pythonpygame
    steps:
      - checkout  # Para obtener el código del repositorio
      # Aquí agregamos los pasos para ejecutar tests, linting, análisis estático, etc.
      - run:
          name: Run tests
          command: | 
                    pytest game
      - run:
          name: Run linting
          command: | 
                    pylint game
      - run:
          name: Run code coverage
          command: |
                    coverage run -m pytest game
                    coverage report -m 

workflows:
  workflow-testing:
    jobs:
      - job-testing
      # Agrega un trabajo para desplegar en Kubernetes usando ArgoCD
      # Este trabajo solo se ejecutará en la rama master/main
